version: '3.0'
services:
  ubuntu:
    build: .
    volumes:
     - .:/data
  frontend:
    build: ./frontend
    ports:
     - 3002:3000
     - 9009:9009
    volumes:
     - ./frontend:/data
    links:
     - backend
    environment:
     - PORT=3000
     - HOST=0.0.0.0
     - CHOKIDAR_USEPOLLING=true
  neo4j:
    image: neo4j:3.2
    ports:
     - 7474:7474
     - 7473:7473
     - 7687:7687
    volumes:
    - ./neo4j/data:/data
    - ./neo4j/conf:/conf
    - ./neo4j/logs:/logs
    - ./neo4j/plugins:/plugins
  backend:
    build: ./backend
    ports:
    - 3003:3000
    links:
    - neo4j
    volumes:
    - ./backend:/data
